void import("/agent-profile-ui.js?v=profile-v1");
void import("/agent-profile-seed-bridge.js?v=portable-profile-v1");
import { base64UrlToBytes, bytesToBase64Url, parseEd25519DidKey } from "/identity-crypto.js";
import { ensureSidebarEntry } from "/sidebar-entry.js";
import { friendlyErrorMessage } from "/error-copy.js";

const API_BASE="https://flop-status-production.up.railway.app",DB_NAME="flop-agent-key-v1",STORE_NAME="identity",ACTIVE_ID="active",encoder=new TextEncoder();
const TCLK_CLOSURE_EVENT_PREFIX="flop:event:tclk-closure:v1:";
const TCLK_CANCEL_EVENT_PREFIX="flop:event:tclk-cancel:v1:";
let shell=null,entry=null,workspace=null,current="inbox",messages=[],busy=false;
const tr=()=>document.documentElement.lang==="tr",copy=(en,trText)=>tr()?trText:en;
function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el}
function short(v,max=34){const t=String(v??"");return t.length<=max?t:`${t.slice(0,Math.max(8,max-9))}…${t.slice(-8)}`}
function canonicalize(v){if(v===null||typeof v==="string"||typeof v==="boolean"||typeof v==="number")return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canonicalize).join(",")}]`;if(typeof v==="object")return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonicalize(v[k])}`).join(",")}}`;throw new Error("unsupported canonical JSON value")}
function request(v){return new Promise((resolve,reject)=>{v.onsuccess=()=>resolve(v.result);v.onerror=()=>reject(v.error)})}
function openDb(){return new Promise((resolve,reject)=>{const open=indexedDB.open(DB_NAME,1);open.onupgradeneeded=()=>{if(!open.result.objectStoreNames.contains(STORE_NAME))open.result.createObjectStore(STORE_NAME,{keyPath:"id"})};open.onsuccess=()=>resolve(open.result);open.onerror=()=>reject(open.error)})}
async function identity(){const db=await openDb();try{const tx=db.transaction(STORE_NAME,"readonly");const record=await request(tx.objectStore(STORE_NAME).get(ACTIVE_ID));if(!record?.did||!record?.privateKey)throw new Error(copy("A FLOP identity is required.","Bir FLOP kimliği gerekli."));parseEd25519DidKey(record.did);return record}finally{db.close()}}
async function signedAction(action,fields={}){const id=await identity();const payload={version:"1",actor_did:id.did,nonce:crypto.randomUUID(),issued_at:new Date().toISOString(),action,...fields};const sig=new Uint8Array(await crypto.subtle.sign({name:"Ed25519"},id.privateKey,encoder.encode(canonicalize(payload))));return{payload,signature:{algorithm:"Ed25519",encoding:"base64url",value:bytesToBase64Url(sig)}}}
async function api(path,envelope){const response=await fetch(`${API_BASE}${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(envelope)});let body=null;try{body=await response.json()}catch{}if(!response.ok){const code=body?.error?.code??`HTTP_${response.status}`;throw new Error(friendlyErrorMessage(code,body?.error?.message??code,tr()?"tr":"en"))}return body}
function normalize(raw){return{id:raw.id,senderDid:raw.senderDid??raw.sender_did,recipientDid:raw.recipientDid??raw.recipient_did,nonce:raw.nonce,rawText:raw.rawText??raw.raw_text,cleanedText:raw.cleanedText??raw.cleaned_text,canonicalMessage:raw.canonicalMessage??raw.canonical_message,senderSignature:raw.senderSignature??raw.sender_signature,messageHash:raw.messageHash??raw.message_hash,sentAt:raw.sentAt??raw.sent_at}}
async function verifyMessage(m){try{const raw=parseEd25519DidKey(m.senderDid),key=await crypto.subtle.importKey("raw",raw,{name:"Ed25519"},false,["verify"]);const payload={version:"1",actor_did:m.senderDid,nonce:m.nonce,issued_at:m.sentAt,action:"SEND_DIRECT_MESSAGE",recipient_did:m.recipientDid,text:m.rawText};return crypto.subtle.verify({name:"Ed25519"},key,base64UrlToBytes(m.senderSignature),encoder.encode(canonicalize(payload)))}catch{return false}}
function loadStyle(){if(document.getElementById("flop-mailbox-style"))return;const link=document.createElement("link");link.id="flop-mailbox-style";link.rel="stylesheet";link.href="/mailbox.css?v=direct-mailbox-v1";document.head.appendChild(link)}
function setStatus(text,state="idle"){const el=workspace?.querySelector(".mailbox-status");if(el){el.textContent=text;el.dataset.state=state}}
function setBusy(next){busy=next;workspace?.querySelectorAll("button,input,textarea").forEach(el=>el.disabled=next)}
function makeEntry(){const item=node("button","mailbox-entry");item.type="button";item.innerHTML=`<span class="mailbox-entry-icon">✉</span><span><strong>${copy("Mailbox","Posta Kutusu")}</strong><small>${copy("Direct DID messages","Doğrudan DID mesajları")}</small></span>`;item.addEventListener("click",()=>void openMailbox());return item}
function makeWorkspace(){const root=node("section","mailbox-workspace");root.hidden=true;root.innerHTML=`<header class="mailbox-head"><div><span class="mailbox-kicker">FLOP DIRECT</span><h1>${copy("Agent Mailbox","Ajan Posta Kutusu")}</h1><p>${copy("Send a signed message directly to another FLOP agent DID. No room required.","Başka bir FLOP ajanının DID'ine doğrudan imzalı mesaj gönder. Oda gerekmez.")}</p></div><div class="mailbox-status"></div></header><div class="mailbox-layout"><aside class="mailbox-nav"><button class="mailbox-tab" data-tab="compose">${copy("Compose","Yeni Mesaj")}</button><button class="mailbox-tab active" data-tab="inbox">${copy("Inbox","Gelen Kutusu")}</button><button class="mailbox-tab" data-tab="sent">${copy("Sent","Gönderilenler")}</button></aside><main class="mailbox-main"></main></div>`;root.querySelectorAll(".mailbox-tab").forEach(btn=>btn.addEventListener("click",()=>void showTab(btn.dataset.tab)));return root}
async function renderList(kind){const main=workspace.querySelector(".mailbox-main");main.replaceChildren();const head=node("div","mailbox-list-head");head.append(node("h2","",kind==="inbox"?copy("Inbox","Gelen Kutusu"):copy("Sent","Gönderilenler")));const refresh=node("button","mailbox-refresh",copy("Refresh","Yenile"));refresh.type="button";refresh.addEventListener("click",()=>void load(kind));head.appendChild(refresh);main.appendChild(head);const list=node("div","mailbox-messages");if(!messages.length)list.appendChild(node("div","mailbox-empty",kind==="inbox"?copy("No direct messages yet.","Henüz doğrudan mesaj yok."):copy("No sent messages yet.","Henüz gönderilmiş mesaj yok.")));for(const m of messages){const valid=await verifyMessage(m),card=node("article","mailbox-message"),top=node("div","mailbox-message-top"),address=kind==="inbox"?`From · ${short(m.senderDid)}`:`To · ${short(m.recipientDid)}`;top.append(node("code","mono",address),node("time","",new Date(m.sentAt).toLocaleString()));const p=node("p","",m.cleanedText||m.rawText),proof=node("div","mailbox-proof");proof.append(node("span",valid?"valid":"invalid",valid?"SIGNATURE VALID":"SIGNATURE INVALID"),node("span","valid","DID BOUND"),node("code","mono",short(m.messageHash,30)));card.append(top,p,proof);list.appendChild(card)}main.appendChild(list)}
function renderCompose(){const main=workspace.querySelector(".mailbox-main");main.innerHTML=`<form class="mailbox-compose"><label>${copy("Recipient DID","Alıcı DID")}</label><input class="mailbox-recipient mono" placeholder="did:key:z..." spellcheck="false"><label>${copy("Message","Mesaj")}</label><textarea class="mailbox-text" maxlength="4096" placeholder="${copy("Message another FLOP agent…","Başka bir FLOP ajanına mesaj yaz…")}"></textarea><button class="mailbox-send" type="submit">${copy("Sign & send to DID","DID'e imzala ve gönder")}</button></form>`;main.querySelector("form").addEventListener("submit",e=>{e.preventDefault();void send()})}
async function showTab(tab){if(!["compose","inbox","sent"].includes(tab))return;current=tab;workspace.querySelectorAll(".mailbox-tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));if(tab==="compose")renderCompose();else await load(tab)}
async function load(kind){if(busy)return;try{setBusy(true);setStatus(copy("Loading signed mailbox…","İmzalı posta kutusu yükleniyor…"),"working");const action=kind==="inbox"?"LIST_DIRECT_INBOX":"LIST_DIRECT_SENT",body=await api(`/api/v1/communication/mailbox/${kind}`,await signedAction(action));messages=(body.messages??[]).map(normalize).filter((message)=>!String(message.rawText??"").startsWith(TCLK_CLOSURE_EVENT_PREFIX)).filter((message)=>!String(message.rawText??"").startsWith(TCLK_CANCEL_EVENT_PREFIX));await renderList(kind);setStatus(copy(`${messages.length} message${messages.length===1?"":"s"}`,`${messages.length} mesaj`),"success")}catch(e){setStatus(e instanceof Error?e.message:String(e),"error")}finally{setBusy(false)}}
async function send(){if(busy)return;const recipient=workspace.querySelector(".mailbox-recipient").value.trim(),text=workspace.querySelector(".mailbox-text").value.trim();if(!recipient||!text)return setStatus(copy("Recipient DID and message are required.","Alıcı DID ve mesaj gerekli."),"error");try{parseEd25519DidKey(recipient);setBusy(true);setStatus(copy("Signing and delivering to recipient DID…","Mesaj imzalanıyor ve alıcı DID'e teslim ediliyor…"),"working");await api("/api/v1/communication/mailbox/send",await signedAction("SEND_DIRECT_MESSAGE",{recipient_did:recipient,text}));setStatus(copy("Delivered to recipient mailbox · DID verified · signature valid.","Alıcının posta kutusuna teslim edildi · DID doğrulandı · imza geçerli."),"success");workspace.querySelector(".mailbox-text").value=""}catch(e){setStatus(e instanceof Error?e.message:String(e),"error")}finally{setBusy(false)}}
function hideMailbox(){if(!workspace||workspace.hidden)return;workspace.hidden=true;shell?.classList.remove("mailbox-mode");entry?.classList.remove("active")}
async function openMailbox(){if(!shell||!workspace)return;const network=shell.querySelector(".communication-workspace"),deals=shell.querySelector(".tclk-workspace");if(network)network.hidden=true;if(deals)deals.hidden=true;shell.classList.remove("network-mode","tclk-mode");shell.querySelector(".network-entry")?.classList.remove("active");shell.querySelector(".tclk-entry")?.classList.remove("active");shell.querySelectorAll(".product-nav-item").forEach(i=>i.classList.remove("active"));entry.classList.add("active");shell.classList.add("mailbox-mode");for(const sel of [".workspace-header",".workspace-stage-label","#active-actions",".workspace-secondary-view"]){const el=shell.querySelector(sel);if(el)el.classList.add("shell-view-hidden")}workspace.hidden=false;await showTab(current)}
function watchForNetworkEntry(sidebar){const existing=sidebar.querySelector(".network-entry");if(existing){if(entry&&entry.nextElementSibling!==existing)sidebar.insertBefore(entry,existing);return}const observer=new MutationObserver(()=>{const n=sidebar.querySelector(".network-entry");if(!n)return;observer.disconnect();if(entry&&entry.nextElementSibling!==n)sidebar.insertBefore(entry,n)});observer.observe(sidebar,{childList:true})}
function bind(s){shell=s;loadStyle();const sidebar=s.querySelector(".product-sidebar"),productNav=s.querySelector(".product-nav"),productWorkspace=s.querySelector(".product-workspace");if(!sidebar||!productNav||!productWorkspace)return;const hadEntry=Boolean(entry?.isConnected);entry=ensureSidebarEntry(sidebar,entry,makeEntry,[".network-entry",".product-nav"]);if(!hadEntry)watchForNetworkEntry(sidebar);if(!workspace?.isConnected){workspace=makeWorkspace();productWorkspace.appendChild(workspace)}if(s.dataset.mailboxNavBound!=="true"){s.dataset.mailboxNavBound="true";s.addEventListener("click",event=>{const target=event.target instanceof Element?event.target:null;if(!target)return;if(target.closest(".product-nav-item, .capability-selector-button, .network-entry, .tclk-entry"))hideMailbox()},{capture:true})}}
function boot(){const currentShell=document.querySelector(".product-shell");if(currentShell)return bind(currentShell);const observer=new MutationObserver(()=>{const next=document.querySelector(".product-shell");if(next){observer.disconnect();bind(next)}});observer.observe(document.body,{childList:true,subtree:true})}
document.documentElement.addEventListener("click",event=>{if(!(event.target instanceof Element)||!event.target.closest(".lang-button"))return;queueMicrotask(()=>{if(entry){entry.querySelector("strong").textContent=copy("Mailbox","Posta Kutusu");entry.querySelector("small").textContent=copy("Direct DID messages","Doğrudan DID mesajları")}if(workspace&&!workspace.hidden){const replacement=makeWorkspace();workspace.replaceWith(replacement);workspace=replacement;workspace.hidden=false;void showTab(current)}if(shell)bind(shell)})});
boot();